name = "ssr-blog"
type = "javascript"
workers_dev = true
account_id = "31f6d0110b1210c0924e578505bbc412"
# zone_id = "Or specified with process.env.CF_ZONE_ID"
# route = "example.com/*"


[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"
watch_dir = "app"

[build.upload]
format = "service-worker"